#redis cluster config
redis.cluster.password=
redis.cluster.max.total=100
redis.cluster.max.idle=20
redis.cluster.min.idle=10
redis.cluster.timeout=2000
redis.cluster.maxAttempts=100
redis.cluster.redisDefaultExpiration=3600
redis.cluster.usePrefix=true
redis.cluster.blockWhenExhausted=true
redis.cluster.maxWaitMillis=3000
redis.cluster.testOnBorrow=false
redis.cluster.testOnReturn=false
redis.cluster.testWhileIdle=true
redis.cluster.minEvictableIdleTimeMillis=60000
redis.cluster.timeBetweenEvictionRunsMillis=30000
redis.cluster.numTestsPerEvictionRun=-1
redis.cluster.defaultExpirationKey=defaultExpirationKey
redis.cluster.expirationSecondTime=300
redis.cluster.preloadSecondTime=280

redis.cluster.index.zero=0
redis.cluster.index.one=1
redis.cluster.index.two=2
redis.cluster.index.three=3

#node info
redis.cluster.node.one=8.154.35.136
redis.cluster.node.one.port=8100

redis.cluster.node.two=8.154.35.136
redis.cluster.node.two.port=8101

redis.cluster.node.three=8.154.35.136
redis.cluster.node.three.port=8102

redis.cluster.node.four=8.154.35.136
redis.cluster.node.four.port=8103

redis.cluster.node.five=8.154.35.136
redis.cluster.node.five.port=8104

redis.cluster.node.six=8.154.35.136
redis.cluster.node.six.port=8105

redis.cluster.node.seven=8.154.35.136
redis.cluster.node.seven.port=8106
